name:                fic-wordpress
version:             0.1.0.0
synopsis:            A REST API interfacing with Wordpress Datbase & Authentication.
#description:
homepage:            https://github.com/Fellowship-For-Intentional-Community/Haskell-Wordpress-API#readme
license:             GPL-3.0
author:              Pavan Rikhi
maintainer:          pavan.rikhi@gmail.com
copyright:           FIC, 2018
category:            Web
extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:        src
  dependencies:       []

executables:
  fic-wordpress:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - fic-wordpress
