name:                fic-wordpress
version:             0.1.0.0
synopsis:            A REST API interfacing with Wordpress Datbase & Authentication.
#description:
homepage:            https://github.com/Fellowship-For-Intentional-Community/Haskell-Wordpress-API#readme
license:             GPL-3.0
author:              Pavan Rikhi
maintainer:          pavan.rikhi@gmail.com
copyright:           FIC, 2018
category:            Web
extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - flow
  - mtl

library:
  source-dirs:        src
  dependencies:
    - aeson
    - persistent
    - persistent-template
    - resource-pool
    - servant
    - servant-server
    - text
    - time
    - wai

executables:
  fic-wordpress:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - fic-wordpress
      - monad-logger
      - persistent-mysql
      - warp
